import GetALimo from "@components/home/GetALimo";
import Hero from "@components/home/Hero";
import OurFleet from "@components/home/OurFleet";
import Section2 from "@components/home/Section2";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Hero />
        <Section2 />
        <OurFleet />
        <GetALimo />
      </main>
    </div>
  );
};

export default Home;
